import kconfiglib
from dataclasses import dataclass

@dataclass
class FileSource:
    menu_name: str
    source_file: str

@dataclass
class ConfigFile:
    filename: str
    menu_sources: list[FileSource]

# Kconfiglib will be encoded in the following way: 
# The Main kconfigs targets (actuallly paths with plain kconfigs)
# Will generate a tree structure, like 

# /home/dir/tree/Kconfig
# /home/dir/tree/amen/Kconfig
# /home/dir/house/Kconfig

# Receiving also a base path , assume /home/dir/ has base will generate following tree
# /home/dir/
           # tree
                 # Kconfig
                 # amen
                         # Kconfig
           # house
                 # Kconfig

# Then the following happening functions should exist to return the following 
# list[KconfigFile]
# A list with tuples, where first element is the files to create, 
# and second one is a list contain a tuple with the name of the menu and the source file to be present there

def remove_base_path(base_path : str, path: str) -> str:
    return path[len(base_path):]

class Tree:
    def __init__(self, base_path : str):
        self.base_path = base_path
        self.root_node = Node(base_path)

    def add_path(self, path : str):
        rest = remove_base_path(self.base_path, path)
        path_list = [self.base_path] + rest.split("/")
        self.root_node.add_path_str(path_list)

    # Here all main Kconfig actually files will be on a list flat on the autogenerated Kconfig
    def get_kconfigs_info_flat(self) -> list[ConfigFile]:
        kconfig_files : list[ConfigFile] = []
        kconfig_file_sources = self.root_node.find_kconfig_files("", self.base_path)
        kconfig_file = ConfigFile(filename=(self.base_path + "/Kconfig").replace("//","/"), menu_sources=kconfig_file_sources)
        kconfig_files.append(kconfig_file)
        return kconfig_files
    
    # Here in the tree there are intermediary Kconfig files, but only when the number of childs is superior to one 
    # If not it is passed to the top 
    def get_kconfigs_info_organized(self) -> list[ConfigFile]:
        extra_configs: list[ConfigFile] = []
        
        # Run the organized search
        root_sources = self.root_node.find_kconfig_files_organized("", self.base_path, extra_configs)
        
        # Create the primary entry point (the root Kconfig)
        root_filename = (self.base_path + "/Kconfig").replace("//", "/")
        main_kconfig = ConfigFile(filename=root_filename, menu_sources=root_sources)
        
        # Return all discovered intermediary configs plus the main one
        # A errro somewhere on the code is letting sometimes recursive entries on Kconfig 
        # filenames that are referncing themselves, this function is explicity avoiding this
        to_return = extra_configs + [main_kconfig]
        non_rec_return : list[ConfigFile] = []
        for c in to_return:
            isrec = False
            for e in c.menu_sources:
                if(c.filename == e.source_file):
                    isrec = True
                    break
            if(not isrec):
                non_rec_return.append(c)
                    
        return non_rec_return
        
class Node:
    def __init__(self, name: str):
        self.name = name
        self.childs: list["Node"] = []

    def create_long_node(self, parts: list[str]) -> Node:
        if not parts:
            raise ValueError("Cannot call this with 0 parts")
        node = Node(parts[0])
        if len(parts) > 1:
            node.childs.append(self.create_long_node(parts[1:]))
        return node
    
    def add_path_str(self, parts: list[str]) -> bool:
        if not parts:
            return False
        if parts[0] != self.name:
            return False
        if len(parts) == 1:
            return True
        for child in self.childs:
            if child.add_path_str(parts[1:]):
                return True
        self.childs.append(self.create_long_node(parts[1:]))
        return True
    
    def pretty_print(self, prefix: str = "", is_last: bool = True):
        connector = "└── " if is_last else "├── "
        print(prefix + connector + self.name)

        prefix += "    " if is_last else "│   "

        for i, child in enumerate(self.childs):
            is_child_last = i == len(self.childs) - 1
            child.pretty_print(prefix, is_child_last)
    def clean_menus_path(self, rel_path : str, base_path : str) -> str :
            rel_path = rel_path + "/"
            rel_path = rel_path.replace("//","/")
            while(base_path in rel_path):
                rel_path = remove_base_path(base_path, rel_path)
            
            if(len(rel_path) > 0 and rel_path[-1] == "/"):
                rel_path = rel_path[:-1]
            return rel_path

    def find_kconfig_files(self, rel_path : str, base_path : str) -> list[FileSource]:
        if(self.name == "Kconfig"):
            rel_path = self.clean_menus_path(rel_path, base_path)
            file_path = base_path + rel_path + "/Kconfig"
            file_path = file_path.replace("//","/")
            return [FileSource(menu_name=rel_path, source_file=file_path)]
        l : list[FileSource] = []
        for ch in self.childs:
            l += ch.find_kconfig_files(rel_path + "/" + self.name, base_path)
        return l
    

    def find_kconfig_files_organized(self, rel_path: str, base_path: str, extra_configs: list[ConfigFile]) -> list[FileSource]:
        # Determine if this is the root node
        is_root = (self.name == base_path)
        
        # Build the relative path for this node (excluding root name)
        if is_root:
            current_rel = ""
        else:
            # Join rel_path and self.name, ensuring no double slashes
            current_rel = (rel_path + "/" + self.name).replace("//","/")

        # Base Case: This node is a Kconfig file
        if self.name == "Kconfig":
            full_path = (base_path + "/" + rel_path + "/Kconfig").replace("//", "/")
            return [FileSource(menu_name=rel_path, source_file=full_path)]

        # Recursive Step: Collect all sources from children
        all_child_sources: list[FileSource] = []
        for ch in self.childs:
            all_child_sources += ch.find_kconfig_files_organized(current_rel, base_path, extra_configs)

        # Aggregation Logic:
        # If we have multiple sources and we aren't the root, we create an intermediary file
        if len(all_child_sources) > 1 and not is_root:
            # Create a path for the auto-generated Kconfig in this directory
            target_dir = (base_path + "/" + current_rel).replace("//", "/")
            target_file = target_dir + "/Kconfig"
            
            # Save the new ConfigFile object
            extra_configs.append(ConfigFile(filename=target_file, menu_sources=all_child_sources))
            
            # Return a single source pointing to this NEW file for the parent node
            return [FileSource(menu_name=current_rel.replace("//","/"), source_file=target_file.replace("//","/"))]

        # If it's a single source or root, just pass the sources up
        return all_child_sources

        

def create_kconfigs(file_list : list[ConfigFile]):
    for file in file_list:
        with open(file.filename, "w") as f:
            for menu in file.menu_sources:
                f.write(f'menu "{menu.menu_name}"\n\n')
                f.write(f'source "{menu.source_file}"\n')
                f.write(f'\nendmenu\n')

if __name__ == "__main__":
    b = "/home/dir/" 

    ps = ["/home/dir/tree/chocolate/tropical/Kconfig",
     "/home/dir/tree/amen/Kconfig",
     "/home/dir/house/Kconfig"]

    tree = Tree(b)
    for p in ps:
        tree.add_path(p)
    tree.root_node.pretty_print()
    kconfig_info = tree.get_kconfigs_info_organized()
    for c in kconfig_info:
        print(c)
    #create_kconfigs(kconfig_info)
